// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cscr_samples_Cpp
List cscr_samples_Cpp(List func_list, List init_list, List free_list, List arg_list, arma::vec tout, int Nmax, double rel_tol, int nsmp, int ncore);
RcppExport SEXP CFC_cscr_samples_Cpp(SEXP func_listSEXP, SEXP init_listSEXP, SEXP free_listSEXP, SEXP arg_listSEXP, SEXP toutSEXP, SEXP NmaxSEXP, SEXP rel_tolSEXP, SEXP nsmpSEXP, SEXP ncoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type func_list(func_listSEXP);
    Rcpp::traits::input_parameter< List >::type init_list(init_listSEXP);
    Rcpp::traits::input_parameter< List >::type free_list(free_listSEXP);
    Rcpp::traits::input_parameter< List >::type arg_list(arg_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tout(toutSEXP);
    Rcpp::traits::input_parameter< int >::type Nmax(NmaxSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type nsmp(nsmpSEXP);
    Rcpp::traits::input_parameter< int >::type ncore(ncoreSEXP);
    __result = Rcpp::wrap(cscr_samples_Cpp(func_list, init_list, free_list, arg_list, tout, Nmax, rel_tol, nsmp, ncore));
    return __result;
END_RCPP
}
